#version
version: "1.0"

permalink: /:year/:month/:day/:title/

# 站点设置
title: "Catatan Komputer"
email: ritnesaif@gmail.com
description: "Catatan Aktifitas Komputer"
keywords: "Saifulindo"

# 用户信息设置
github_username: saifulindo

# Markdown设置
kramdown:
  input:  GFM
  use_coderay: true
  coderay:
    coderay_line_numbers: nil
    syntax_highlighter: coderay



# 地址设置
baseurl: "/myblog"
url: "http://saifulindo.github.io"


# 分页设置
paginate: 10
paginate_path: "page/:num"

#scss设置
sass:
    sass_dir: /assets/stylesheet
    style: :compressed

gems: [jekyll-paginate]

